logService: log-service
protocol: http

zuul:
  ignoredServices: '*'
  host:
    maxTotalConnections: 1000
    maxPerRouteConnections: 1000
  prefix: /api
  routes:
    product-catalog-service:
      path: /catalog/**
      sensitiveHeaders: null
      serviceId: product-catalog-service
      stripPrefix: false
    products-service:
      path: /products/**
      sensitiveHeaders: null
      serviceId: products-service
      stripPrefix: false
    log-service:
      path: /logs/**
      sensitiveHeaders: null
      serviceId: log-service
      stripPrefix: false