server:
  port: 8080

spring:
  application:
    name: ecommerce-api-gateway

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      registryFetchIntervalSeconds: 5
      defaultZone: http://localhost:8081/eureka/
      instance:
        preferedIpAddress: true

zuul:
  ignoredServices: '*'
  host:
    maxTotalConnections: 1000
    maxPerRouteConnections: 1000
  prefix: /api
  routes:
    product-catalog-service:
      path: /catalog/**
      sensitiveHeaders: null
      serviceId: product-catalog-service
      stripPrefix: false
    products-service:
      path: /products/**
      sensitiveHeaders: null
      serviceId: products-service
      stripPrefix: false
    log-service:
      path: /logs/**
      sensitiveHeaders: null
      serviceId: log-service
      stripPrefix: false

## Configuring info endpoint
info:
  appName: ${spring.application.name}
  description: API Gateway for ecommerce application
  version: 1.0.0