product-catalog:
  test:
    prop: APPLICATION Welcome to config server prop
    
test:
    message: From Application under project folder
    
    
spring:
  jpa:
    showSql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
