spring:
  boot:
    admin:
      routes:
        endpoints: env, metrics, trace, jolokia, info, configprops
      client:
        username: ${ADMIN_USER}
        password: ${ADMIN_PASS}
        #instance:
          #metadata:
            #user:
              #name: ${spring.security.user.name}
              #password: ${spring.security.user.password}
  #security:
    #user:
      #name: client
      #password: client