server:
  port: 8081

spring:
  application:
    name: Spring-boot-admin
  boot:
    admin:
      routes:
        endpoints: env, metrics, trace, jolokia, info, configprops
      client:
        username: admin
        password: admin
        #instance:
          #metadata:
            #user:
              #name: ${spring.security.user.name}
              #password: ${spring.security.user.password}
  #security:
    #user:
      #name: client
      #password: client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
      instance:
        preferedIpAddress: true

## Configuring info endpoint
info:
  java-vendor: ${java.specification.vendor}
  app: admin-ui
  name: Spring boot ecommerce admin ui Service Application
  description: This is my first spring boot application microservice
  version: 1.0.0