server:
  port: 8081

spring:
  application:
    name: Spring-boot-admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
      instance:
        preferedIpAddress: true

