## for database properties have to connect with config server

## for spring boot admin using config server

## config server referred for config server itself

management:
  endpoints:
    web:
      exposure:
        include: '*'
