server:
  port: 8082

spring:
  application:
    name: eureka-service-registry

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
      instance:
        preferedIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
## Configuring info endpoint
info:
  java-vendor: ${java.specification.vendor}
  app: eureka-service-registry
  name: Spring Eureka server Service Application
  description: This is my first spring boot application microservice
  version: 1.0.0