server:
  port: 8081

spring:
  application:
    name: eureka-service-registry

eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
      instance:
        preferedIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

## Configuring info endpoint
info:
  appName: ${spring.application.name}
  description: Eureka server for ecommrce application
  version: 1.0.0