server:
  port: 8082

spring:
  application:
    name: ecommerce-config-service

---
spring:
  cloud:
    config:
      uri: https://github.com/pravin02/Ecommerce-Microservices/config-props
      server:
        bootstrap: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    instance:
      preferedIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

## Configuring info endpoint
info:
  appName: ${spring.application.name}
  description: Products service to serve products list for ecommerce
  version: 1.0.0
