spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pravin02/ecommerce-config-props.git
          username:
          password:
          defaultLabel: main
          cloneOnStart: true
          skipSslValidation: true
          refreshRate: 10800
          searchPaths: services/*

management:
  endpoints:
    web:
      exposure:
        include: '*'