server:
  port: 8888

spring:
  application:
    name: ecommerce-config-service

---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pravin02/ecommerce-config-props.git
          username:
          password:
          defaultLabel: main
          cloneOnStart: true
          skipSslValidation: true
          refreshRate: 10800
          searchPaths: services/*

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    instance:
      preferedIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

## Configuring info endpoint
info:
  appName: ${spring.application.name}
  description: Products service to serve products list for ecommerce
  version: 1.0.0
