server:
  port: 8084

spring:
  application:
    name: products-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
    instance:
      preferedIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
## Configuring info endpoint
info:
  app: products-service
  name: Spring Products Service Application
  description: This is my first spring boot application microservice
  version: ${version}