server:
  port: 8084

spring:
  application:
    name: products-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
    instance:
      preferedIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'