server:
  port: 8083

spring:
  application:
    name: product-catalog-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
      instance:
        preferedIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'