server:
  port: 8083

spring:
  application:
    name: product-catalog-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
      instance:
        preferedIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
## Configuring info endpoint
info:
  app: product-catalog-service
  name: Spring Product Catalog Service Application
  description: This is my first spring boot application microservice
  version: 1.0.0